version: '3.9'

services:
  # database:
  #   image: mysql:5.7
  #   ports:
  #     - '3307:3306'
  #   environment:
  #      MYSQL_DATABASE: 'tsapp1_dev'
  #      MYSQL_USER: 'root'
  #      MYSQL_PASSWORD: '16e91a0553'
  #      MYSQL_ROOT_PASSWORD: '16e91a0553'
  web:
    build: .
    container_name: tsapp_con
    command:  >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"